[package]
name = "pika"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
clap = { version = "4.5.53", features = ["derive"] }
postcard = { version = "1.1.3", features = ["use-std"] }
redb = "3.1.0"
serde = { version = "1.0.228", features = ["derive"] }
